# Generated by Django 4.2.20 on 2025-04-16 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0003_alter_model_overall_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='dashboard_port',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
