# Generated by Django 5.1.7 on 2025-04-08 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("machine_learning", "0004_model_port"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortRegistry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("port", models.IntegerField(unique=True)),
                ("in_use", models.BooleanField(default=False)),
                (
                    "assigned_to",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
